MIN_HEALTH = 10
MAX_HEALTH = 100

PREY_MIN_STAMINA = 10
PREY_MAX_STAMINA = 100

PREDATOR_MIN_STAMINA = 100
PREDATOR_MAX_STAMINA = 200

MIN_POWER = 1
MAX_POWER = 10

MINIMUM_LEG_COUNT = 0
MAXIMUM_LEG_COUNT = 2

MINIMUM_WING_COUNT = 0
MAXIMUM_WING_COUNT = 2

CLAWS = {1: "NO_CLAWS", 2: "SMALL_CLAWS", 3: "MEDIUM_CLAWS", 4: "LARGE_CLAWS"}

TEETH_MODIFIERS = [3, 6, 9]

REQUIRED_WINGS_TO_FLY = 2
REQUIRED_STAMINA_TO_FLY = 80
FLYING_SPEED = 8
FLYING_STAMINA_COST = 4

REQUIRED_LEGS_TO_RUN = 2
REQUIRED_STAMINA_TO_RUN = 60
RUNNING_SPEED = 6
RUNNING_STAMINA_COST = 4

REQUIRED_LEGS_TO_WALK = 2
REQUIRED_STAMINA_TO_WALK = 40
WALKING_SPEED = 4
WALKING_STAMINA_COST = 2

REQUIRED_LEGS_TO_HOP = 1
REQUIRED_STAMINA_TO_HOP = 20
HOPPING_SPEED = 3
HOPPING_STAMINA_COST = 2

REQUIRED_STAMINA_TO_CRAWL = 1
CRAWLING_SPEED = 1
CRAWLING_STAMINA_COST = 1
